### ISSUE TITLE
Bluetooth not work on Android 11 API 30

### ISSUE THREAD

**Issue by youvita** [Reedyuk/blue-falcon#120] opened 2024-04-30 07:48 UTC
Any help, when I clicked scan is started status. However don't display any bluetooth found.
Noted: Bluetooth and permission is turn on status

<img width="1337" alt="Screenshot 2024-04-30 at 3 14 48 PM" src="https://github.com/Reedyuk/blue-falcon/assets/12288373/b7d7d53b-801d-4a92-af08-6b948a087a8e">
<img width="966" alt="Screenshot 2024-04-30 at 2 43 36 PM" src="https://github.com/Reedyuk/blue-falcon/assets/12288373/9a3cd6fe-a4e8-490f-9c0a-e1c1edac0549">

**Comment by Reedyuk** [comment] 2024-04-30 08:18
It would appear that bluetoothadapter.java is throwing an exception. If you click into it you will see the code and find why this is the case. 
Usually the stacktrace is bigger and you will find the original cause lower down(its cut off on your screenshot).
Chances are, this is an issue with android.bluetooth.BluetoothAdapter(standard android) and not an issue with the blue falcon library.
It could be a permissions issue, seems like there is a fetching of systemService from a context wrapper. - Permission with xml manifest?

**Comment by youvita** [comment] 2024-04-30 09:34
Yes, I also added the permission in manifest. However I tried with other device android version 14 API 34 it's working. That's why I think the issue come from version android device.

**Comment by Reedyuk** [comment] 2024-04-30 13:09
So it works on version 14 API 34 of android. Which version of android does it not work? What is the full stack trace? you will probably find a hint of the error there

**Comment by youvita** [comment] 2024-05-02 02:30
The currently android version 11 API 30 not work. The actually I try run the same source code but the version 11 of android not list bluetooth found. however it's work on version 14 API 34
Noted: both device also turn on bluetooth and clicked scan button.

Device not work
![2024-05-02 09 27 51](https://github.com/Reedyuk/blue-falcon/assets/12288373/cdeb1461-f245-43c7-850c-afb8fba6447e)

Device work
![2024-05-02 09 26 43](https://github.com/Reedyuk/blue-falcon/assets/12288373/e9f7a13a-dbd0-44ef-ba85-cf8fec50f96b)

**Comment by Reedyuk** [comment] 2024-05-02 07:37
Do you have the **full** stacktrace? could you post it in here?

**Comment by youvita** [comment] 2024-05-02 08:27
I'm not sure what is the full stack trace. However I have to explore logs file, may it's can help.

[OnePlus-ONEPLUS-A6000-Android-11_2024-05-02_152223.logcat.zip](https://github.com/Reedyuk/blue-falcon/files/15185633/OnePlus-ONEPLUS-A6000-Android-11_2024-05-02_152223.logcat.zip)

**Comment by Reedyuk** [comment] 2024-05-02 08:38
Having a look now for you

**Comment by Reedyuk** [comment] 2024-05-02 08:40
Are you sure you have the correct permissions:
```

    /**
     * Broadcast Action: The notifys Bluetooth ACL connected event. This will be
     * by BLE Always on enabled application to know the ACL_CONNECTED event
     * when Bluetooth state in STATE_BLE_ON. This denotes GATT connection
     * as Bluetooth LE is the only feature available in STATE_BLE_ON
     *
     * This is counterpart of {@link BluetoothDevice#ACTION_ACL_CONNECTED} which
     * works in Bluetooth state STATE_ON
     *
     * @hide
     */
    @RequiresBluetoothConnectPermission
    @RequiresPermission(android.Manifest.permission.BLUETOOTH_CONNECT)
    @SdkConstant(SdkConstantType.BROADCAST_INTENT_ACTION)
    public static final String ACTION_BLE_ACL_CONNECTED =
            "android.bluetooth.adapter.action.BLE_ACL_CONNECTED";
```

My guess is that you dont have the bluetooth_connect permission.

`public static final String BLUETOOTH_CONNECT = "android.permission.BLUETOOTH_CONNECT";`

**Comment by youvita** [comment] 2024-05-02 08:43
Yes, I'm sure. Because I'm just from from your source code.

<img width="1465" alt="Screenshot 2024-05-02 at 3 42 16 PM" src="https://github.com/Reedyuk/blue-falcon/assets/12288373/d4bb5fe6-56b6-4b79-abd8-82614b95ec6e">

**Comment by Reedyuk** [comment] 2024-05-02 08:47
i would need to spend time looking into this properly, will have to try later when i have a moment. My guess is its something around contexts and permissions used in an older api of android.
Not the best solution but i would propose you don't support the older api bump the minimum up.

**Comment by youvita** [comment] 2024-05-02 08:49
Thanks for your help

**Comment by Reedyuk** [comment] 2024-05-02 12:44
@youvita - i have tried to recreate the issue but because i dont have a physical android device on android 11, i cannot reproduce. The emulator doesnt crash but obviously it doesnt engage with bluetooth.
As a suggestion i could bump the min api level so that android 11 cannot be supported but that wont fix your problem of supporting those devices.

**Comment by youvita** [comment] 2024-05-13 02:38
@Reedyuk,
I have question, it's possible to display bluetooth name instead bluetooth address?
Example: 77:D9:EE:E6:E2:52 -> U6-LR

**Comment by Reedyuk** [comment] 2024-05-13 05:39
Ble devices expose a characteristic called name, you must call this and then in your app, display the value of this characteristic.

**Comment by youvita** [comment] 2024-05-16 01:47
@Reedyuk, Could you update this name bluetooth address instead characteristic as you mention above? 
It's better know the name of Bluetooth device. Thank you for feedback.

![327294141-e9f7a13a-dbd0-44ef-ba85-cf8fec50f96b](https://github.com/Reedyuk/blue-falcon/assets/12288373/0e27c808-4024-4074-b724-6eccc3c8a0da)

**Comment by Reedyuk** [comment] 2024-05-16 07:05
No, as this is only an android thing and also this could have an impact on other users of the library.
It is up to you, the consumer of the library to do this your side.

**Comment by youvita** [comment] 2024-05-17 01:32
It's possible, you can mention the example code here. Thanks for support.

**Comment by Reedyuk** [comment] 2024-05-17 10:49
Sorry, you will have to do that yourself.

The sudo is rather simple:
Detect device, request characteristic of 'name', when you get the value then display.

You could even extend the BluetoothPeripherial, to have a suspend func to get the Mac address.

Then in your client code, you could have a flow of devices mapped to by key to device e.g.
```
val deviceMap: MutableStateFlow<Map<String, BluetoothPeripherial>> = blueFalconClient.peripherals.map {
it.macAddress() to it
}
```

**Closed** 2024-08-13 16:21 UTC
Labels: bug
